disabled_rules:
  - todo
  - nesting
  - no_space_in_method_call
  - nesting
  - void_return
  - implicit_getter
  - trailing_whitespace
excluded:
  - Pods
line_length:
  warning: 140
  error: 140
  ignores_comments: true
